spring.application.name=AppModa
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/appmoda
spring.datasource.username=postgres
spring.datasource.password=Vitoria

# Faz o Spring criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console (útil pra aprender)
spring.jpa.show-sql=true